### ISSUE TITLE
JF17 - Request the implementation of the +/,/- Switch

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#45] opened 2021-02-14 12:01 UTC
It is just below the UFC. It's function is similar to the F16 waypoint switch and is frequently used. It is centered and has a momentary up and a momentary down position.

**Comment by asherao** [comment] 2021-02-21 03:24
Version 1.1(5)
The implementation of the +/,/- Switch works. Requesting longer "-" zone so that the user can see it getting activated. At the moment, when you press the "-" area, it so close to the activated switch that the users finger may cover it.

**Comment by wluc9875** [comment] 2021-02-21 07:52
will check how I can enhance this

**Comment by wluc9875** [comment] 2021-02-25 07:46
touchable zone is now longer

**Comment by asherao** [comment] 2021-02-25 08:10
Touchable zone seems to have been extended. But there is a small area very close to the edge of the iPad, in between the edge of the iPad and the end of the lower clickable zone. Touching in this odd zone will not make a sound, but releasing will. There is no animation associated. Finger is not moved to or from another location on the iPad.

**Comment by wluc9875** [comment] 2021-02-25 09:30
I can't reproduce this one. Nevertheless, I extended the touch area for the fast select decrement to the edge of the UFC. I hope this will help.

**Comment by asherao** [comment] 2021-02-27 13:49
I have noticed that this issue only happens when the Ipad Air 2 is in landscape mode. It works as designed in portrait mode.

**Comment by wluc9875** [comment] 2021-02-27 16:53
I'll need to find a way to test it on an iPad Air 2, whether physical device or simulator.
I'll create a separate GH issue for the touchable zone due for version 1.2 and I'll close this one.

**Closed by wluc9875** 2021-02-27 16:53 UTC
Labels: To be tested, enhancement
