### ISSUE TITLE
AV8B - When BCN is used, the text in the window is not displayed on the iPad

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#40] opened 2021-02-14 11:38 UTC
The BCN button can be pressed either in the sim or the iPad. In the AV8B Ready on the Ramp Instant Mission, there result of pressing the button is that the window displays "ON", justified to the left. This is not shown in the app.

**Comment by asherao** [comment] 2021-02-14 11:40
I have realized that after pressing BCN, it seems that the app no longer gets updates from the game or something. Pressing other commands in the app or in game do not change the windows. I restart the app to get functionality back.

**Comment by wluc9875** [comment] 2021-02-19 14:37
Was a bit tricky to find that one.
Razbam is sending garbage data for ODU 3 (not displayed in DCS, but couldn't be properly converted to String on the iPad)
Will be fixed in 1.1

**Comment by asherao** [comment] 2021-02-21 03:11
Version 1.1(5)
-When BCN is pressed on the iPad or in-game, the correct indications show up except for the "0" in ODU Option 5.

**Comment by wluc9875** [comment] 2021-02-21 07:50
I didn't notice there was content in ODU 5, but only ODU 1 and 2. Do you have steps to reproduce?

**Comment by asherao** [comment] 2021-02-23 00:48
> I didn't notice there was content in ODU 5, but only ODU 1 and 2. Do you have steps to reproduce?

Correction, it's ODU option 3
-Start DCS
-Start Instant Action AB8B Caucasus - Ready On The Ramp
-Press BCN button on the UFC or iPad
-ODU 1 and ODU 2 text is populated on the iPad
-ODU 3 displays a "/" character ingame. It is not represented on the iPad

**Comment by wluc9875** [comment] 2021-02-23 09:11
Is this ODU content useful? Because ODU3 data is where there seems to be random content sent from the AV8 module.

**Comment by asherao** [comment] 2021-02-23 09:29
I don't know.

**Comment by wluc9875** [comment] 2021-02-23 09:31
in that case, let's consider this issue fixed for now.

**Closed** 2021-02-25 07:46 UTC
Labels: To be tested, bug
